# Generated by Django 2.2.6 on 2019-10-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191029_1848'),
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='bot_message',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='user_message',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='autor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='id_conversa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Conversa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
